01-monitoria/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get '/monitoria' => 'home#index' # get '[nome_rota]' => '[controller#método]'

  root 'home#index'

  resources :subscriptions
  resources :students #, only: [:index, :create] # permite APENAS (only) as actions /index, /create e /new
  resources :semesters #, except: [:index, :create] # permite tudo, EXCETO (except) as actions /index e /create
  resources :disciplines
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

01-monitoria/app/models/contact.rb
class Contact < ApplicationRecord
end

01-monitoria/app/models/discipline.rb
class Discipline < ApplicationRecord
    has_many :subscriptions
end

01-monitoria/app/models/semester.rb
class Semester < ApplicationRecord
    has_many :subscriptions
end

01-monitoria/app/models/student.rb
class Student < ApplicationRecord
    has_one :contact
    has_many :subscriptions

    accepts_nested_attributes_for :contact
end

01-monitoria/app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all # chama a view index e adiciona à variavel `disciplines` TODAS as disciplinas
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:descricao, :abreviacao)
    end
end

01-monitoria/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.build_contact # @[objeto].build_[nome-do-campo]
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Estudante criado com sucesso.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Estudante atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Estudante apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(
        :nome, :matricula,
        contact_attributes: [:email, :telefone]
      )
    end
end

01-monitoria/app/views/disciplines/_form.html.erb
<%= form_with(model: discipline, local: true) do |form| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :discipline_descricao %>
  </div>

  <div class="field">
    <%= form.label :abreviacao %>
    <%= form.text_field :abreviacao, id: :discipline_abreviacao %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", class:"button btn btn-primary"%>
  </div>
<% end %>

01-monitoria/app/views/disciplines/_table.html.erb
<table class="table table-hover table-bordered">
<thead>
  <tr>
    <th>Descrição</th>
    <th>Abreviação</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @disciplines.each do |discipline| %>
    <tr>
      <td><%= discipline.descricao %></td>
      <td><%= discipline.abreviacao %></td>
      <td><%= link_to 'Ver', discipline %></td>
      <td><%= link_to 'Editar', edit_discipline_path(discipline) %></td>
      <td><%= link_to 'Apagar', discipline, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

01-monitoria/app/views/disciplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplinas</h1>

<%= render partial: '/disciplines/table' %>  

<br>

<%= link_to 'Nova disciplina', new_discipline_path, { :class => "btn btn-secondary"} %>

01-monitoria/app/views/disciplines/new.html.erb
<h1>Nova Disciplina</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Back', disciplines_path %>

01-monitoria/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
<a class="navbar-brand" href="#">Monitoria</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarColor01">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="<%= home_index_path %>">Home</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="<%= students_path %>">Alunos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= disciplines_path %>">Disciplinas</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= semesters_path %>">Semestres</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= subscriptions_path %>">Inscrições</a>
    </li>
  </ul>
</div>
</nav>

01-monitoria/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monitoria</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>    

  <body>
  <%= render partial: 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </body>
</html>

01-monitoria/app/views/semesters/_form.html.erb
<%= form_with(model: semester, local: true) do |form| %>
  <% if semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
      <% semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :semester_ano %>
  </div>

  <div class="field">
    <%= form.label :periodo %>
    <%= form.number_field :periodo, id: :semester_periodo %>
  </div>

  <div class="field">
    <%= form.label :inicio %>
    <%= form.date_select :inicio, id: :semester_inicio %>
  </div>

  <div class="field">
    <%= form.label :fim %>
    <%= form.date_select :fim, id: :semester_fim %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", class:"button btn btn-primary"%>
  </div>
<% end %>

01-monitoria/app/views/semesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Semesters</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Ano</th>
      <th>Periodo</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semesters.each do |semester| %>
      <tr>
        <td><%= semester.ano %></td>
        <td><%= semester.periodo %></td>
        <td><%= semester.inicio %></td>
        <td><%= semester.fim %></td>
        <td><%= link_to 'Show', semester %></td>
        <td><%= link_to 'Edit', edit_semester_path(semester) %></td>
        <td><%= link_to 'Destroy', semester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semester', new_semester_path, { :class => "btn btn-secondary"} %>

01-monitoria/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :nome, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :nome, id: :student_nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :matricula, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :matricula, id: :student_matricula, class: "form-control"  %>
    </div>
  </div>

  <%= form.fields_for :contact do |contato| %>
    <div class="form-group row">
      <%= form.label :email, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= contato.text_field :email, id: :student_email, class: "form-control"  %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :telefone, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= contato.text_field :telefone, id: :student_telefone, class: "form-control"  %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "Salvar", class:"button btn btn-primary"%>
  </div>
<% end %>

01-monitoria/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.nome %></td>
        <td><%= student.matricula %></td>
        <td><%= link_to 'Detalhes', student %></td>
        <td><%= link_to 'Editar', edit_student_path(student) %></td>
        <td><%= link_to 'Apagar', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo aluno', new_student_path, { :class => "btn btn-secondary"} %>

01-monitoria/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @student.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @student.matricula %>
</p>

<%= link_to 'Editar', edit_student_path(@student) %> |
<%= link_to 'Voltar', students_path %>

01-monitoria/app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nota %>
    <%= form.text_field :nota, id: :subscription_nota %>
  </div>

  <div class="field">
    <%= form.label :cre %>
    <%= form.text_field :cre, id: :subscription_cre %>
  </div>

  <div class="field">
    <%= form.label :selecionado %>
    <%= form.check_box :selecionado, id: :subscription_selecionado %>
  </div>

  <div class="field">
    <%= form.label :form_voluntario %>
    <%= form.datetime_select :form_voluntario, id: :subscription_form_voluntario %>
  </div>

  <div class="field">
    <%= form.label :form_relatorio %>
    <%= form.datetime_select :form_relatorio, id: :subscription_form_relatorio %>
  </div>

  <div class="field">
    <%= form.label :discipline_id %>
    <%= collection_select(:subscription, :discipline_id, @disciplinas, :id, :descricao) %>
  </div>

  <div class="field">
    <%= form.label :semester_id %>
    <%= collection_select(:subscription, :semester_id, @semestres, :id, :ano) %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= collection_select(:subscription, :student_id, @alunos, :id, :matricula) %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", class:"button btn btn-primary"%>
  </div>
<% end %>

01-monitoria/app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inscrições</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nota</th>
      <th>Cre</th>
      <th>Selecionado</th>
      <!--
      <th>Form voluntario</th>
      <th>Form relatorio</th>
      -->
      <th>Discipline</th>
      <th>Semester</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.nota %></td>
        <td><%= subscription.cre %></td>
        <td><%= subscription.selecionado %></td>
        <!--
        <td><%= subscription.form_voluntario %></td>
        <td><%= subscription.form_relatorio %></td>
        -->
        <td><%= subscription.discipline.descricao %></td>
        <td><%= subscription.semester.ano %>.<%= subscription.semester.periodo %></td>
        <td><%= subscription.student.nome %> (<%= subscription.student.matricula %>)</td>
        <td><%= link_to 'Enviar', subscription %></td>
        <td><%= link_to 'Editar', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Apagar', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Inscrição', new_subscription_path, { :class => "btn btn-secondary"} %>